### ISSUE TITLE
Kamon 2.0

### ISSUE THREAD

**Issue by dispalt** [bogdanromanx/kamon-monix#2]
Did you ever figure out how to rejig this to work with Kamon 2.0?

I added this, and it seemed to mostly work minus parallel calls (for which I have no idea why they don't work).

```

kanela.modules {
  executor-service {
    within += "monix..*"
  }
}
```

**Comment by bogdanromanx** [comment]
I never got around to upgrade to the stable monix 3.x release and kamon 2.x, but it's something that I'd like very much to do. I will plan some time in the upcoming weeks to sort this out.

**Comment by rhande-mdsol** [comment]
Hi,

Is this `kamon-monix ` supported for Scala 2.13 ? I have two versions of Scala and is giving error for 2.13

**Comment by bogdanromanx** [comment]
Hi @rhande-mdsol, I'm in the process of porting the implementation upstream, please follow this PR instead (I will archive this repo once the PR will be merged): https://github.com/kamon-io/Kamon/pull/879.

**Comment by rhande-mdsol** [comment]
Hi @bogdanromanx , will it be integrated with `kamon-io` itself ?

Thanks in advance

**Comment by bogdanromanx** [comment]
That's the idea, yes.
